import type { Metadata } from "next";
import { Geist, Geist_Mono,Anaheim,Caprasimo } from "next/font/google";
import "./globals.css";
// import { NavbarDemo } from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const anaheim = Anaheim({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-anaheim',
});

const caprasimo =Caprasimo({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-caprasimo',

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${anaheim.variable} ${caprasimo.variable} antialiased`}
       
      >
        
        {children}
      </body>
    </html>
  );
}
